const SHOWMODAL = 'SHOWMODAL';
const HIDEMODAL = 'HIDEMODAL';
const UPDATECONTENT = 'UPDATECONTENT';
const INITIALMESSAGE = 'INITIALMESSAGE'

export { SHOWMODAL, HIDEMODAL, UPDATECONTENT, INITIALMESSAGE };
